version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: church-postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: church
    ports:
      - 5432:5432
    networks:
      - docker
networks:
  docker:
